import turtle

t = turtle.Turtle()
t.pensize(2)
t.speed(1)
t.penup()
t.bk(150)
t.rt(90)
t.bk(150)
t.rt(15)
t.pendown()
t.begin_fill()
for i in range(10):
    t.rt(i+1)
    t.fd(i)
t.lt(135)
for i in range(13):
    t.rt(i+1.5)
    t.fd(i)
for i in range(13):
    t.lt(i+1)
    t.fd(i)
t.lt(122)
t.fd(160)
t.rt(135)
for i in range(10):
    t.lt(i+2)
    t.fd(i)
for i in range(8):
    t.rt(i+2)
    t.fd(i)
for i in range(10):
    t.lt(i+2)
    t.fd(i)
t.rt(116)
for i in range(10):
    t.lt(i+1)
    t.fd(i)
t.rt(135)
for i in range(13):
    t.lt(i+1.5)
    t.fd(i)
for i in range(13):
    t.rt(i+1)
    t.fd(i)
t.rt(122)
t.fd(160)
t.bk(160)
t.lt(120)
t.fd(50)
for i in range(5):
    t.lt(i+1.5)
    t.fd(i)
t.rt(90)
for i in range(5):
    t.lt(i+1.5)
    t.fd(i)
t.fd(58)
t.end_fill()
t.rt(65)
t.fillcolor('white')
t.begin_fill()
t.fd(158)
t.rt(135)
for i in range(9):
    t.lt(i+2)
    t.fd(i)
t.rt(99)
t.fd(167)
t.end_fill()
t.rt(115)
t.fd(40)
t.bk(40)
t.lt(115)
t.bk(167)
t.lt(99)
for i in range(1):
    t.lt(12)
    t.fd(10)
for i in range(8):
    t.rt(i+2)
    t.fd(i)
for i in range(10):
    if i == 4:
        t.begin_fill()
    t.lt(i+2)
    t.fd(i)
t.rt(132)
t.fd(163)
t.rt(60)
t.fd(39)
t.end_fill()
t.lt(60)
t.bk(70)
t.pencolor('white')
t.fillcolor('red')
t.rt(45)
t.begin_fill()
t.fd(32.5)
t.rt(90)
t.fd(32.5)
for i in range(7):
    t.rt(i+6)
    t.fd(i-0.5)
for i in range(6):
    t.lt(i + 7)
    t.fd(i - 0.1)
t.rt(75)
t.fd(15)
t.rt(55)
t.fd(39)
t.rt(50)
t.fd(15)
t.rt(105)
for i in range(8):
    t.lt(i+7)
    t.fd(i)
for i in range(6):
    t.rt(i + 10)
    t.fd(i - 0.5)
t.end_fill()
t.rt(32)
t.penup()
t.fd(17)
t.fillcolor('white')
t.begin_fill()
t.rt(180)
t.circle(15)
t.end_fill()
t.lt(90)
t.fd(5)
t.rt(90)
t.fillcolor('red')
t.pencolor('red')
t.begin_fill()
t.circle(13)
t.end_fill()
t.lt(90)
t.fd(20)
t.pencolor('white')
t.fillcolor('white')
t.begin_fill()
for i in range(6):
    t.fd(10)
    t.rt(135)
t.end_fill()
t.lt(90)
t.fd(20)
t.lt(90)
t.fd(5)
t.write('J', font=('times new roman', 35, 'normal'))
t.fd(45)
t.pencolor('black')
t.write('B', font=('times new roman', 35, 'normal'))
t.bk(75)
t.write('K', font=('times new roman', 35, 'normal'))
t.lt(90)
t.fd(115)
t.rt(90)
t.bk(5)
t.write('3', font=('times new roman', 35, 'normal'))
t.pencolor('white')
t.fd(51.5)
t.write('90', font=('times new roman', 35, 'normal'))
t.fd(23)
t.pencolor('black')
t.write('1', font=('times new roman', 35, 'normal'))
t.fillcolor('black')
t.rt(90)
t.fd(200)


turtle.mainloop()
